version: '3.6'
services:
  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "mysecretpassword"
      MYSQL_ROOT_USER: "root"
      MYSQL_DATABASE: "mpdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local